spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/userdb
    username: fara
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

company:
  service:
    url: http://companyservice:8081
