version: '3.8'

services:
  app:
    build: services
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/userdb
      - SPRING_DATASOURCE_USERNAME=fara
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_USER=fara
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=userdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
